### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by MarijaBircevic** [alptium/marija.bircevic#2]

**Comment by MarijaBircevic** [comment]
Done

**Comment by valentinajemuovic** [comment]
@MarijaBircevic:

1. Please delete the files, because they were incorrectly created in your root directory: 
1.1. marija.bircevic\.classpath
1.2. marija.bircevic\.project
1.3. marija.bircevic\.project
1.4. marija.bircevic\hello-world (it was created as a file)
2. I see the folder is called hello-worldd, but it should be named hello-world

**Comment by MarijaBircevic** [comment]
Yes, like I wrote you on Viber I had a big problems with "Push origin"
part, so I tried on many different ways to solve a problem (uninstall
programs, deleting projects, some things from you tube) and one of them was
to add different name :D
But actually, the problem was in location for saving project (like you
said) even if I chose same place where is Git Hib repository. So I moved it
manualy from one folder in other and it worked.

**Comment by valentinajemuovic** [comment]
@MarijaBircevic, I now tried opening in Eclipse. but got an error. So I will contact you during next few days to do screenshare so that we can fix this point.

**Comment by MarijaBircevic** [comment]
If you opened it successfuly first time, maby you cant now because i
deleted files .classpath and .project. I noticed that that files I had in
the other projects too (Calculator and Gradebook) so I deleted them and
from that projects.
In any case, it would be good to do screenshare with me, to help me to fix
this problem before next tasks. Thank you.

>

**Comment by valentinajemuovic** [comment]
@MarijaBircevic correct now.
